apiVersion: v1
kind: Service
metadata:
  name: hello-kubernetes-nodeport
  labels:
    app.kubernetes.io/name: hello-kubernetes
    app.kubernetes.io/component: service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: hello-kubernetes
    app.kubernetes.io/component: application
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30000
